### ISSUE TITLE
Add ability to set separator character

### ISSUE THREAD

**Issue by Daenyth** [davenverse/cormorant#27]
I have some TSV files that would be otherwise a good fit for this, so it would be nice if they could be supported directly

**Comment by ChristopherDavenport** [comment]
Set seperator file for the parser? They are supported via the Printer already.

**Comment by Daenyth** [comment]
Yes, I meant for the parser. I glanced at the code and it wasn't clear to me that I can set it. Did I miss something?

**Comment by ChristopherDavenport** [comment]
Currently the TSV could be implemented specially, does that then put `\t` in the special characters section as well? Would likely be easiest to copy paste and then switch the `COMMA` to `TAB`. I can try to get to that here shortly

**Comment by Daenyth** [comment]
Generally, yes `\t` becomes a special character which needs escaping - it's treated like the comma in a normal csv, at least to the extent that any csv/tsv file is standard...

**Comment by wedens** [comment]
Another common separator is `|`.

**Comment by ChristopherDavenport** [comment]
So I added tsv, I can add `|` as well. I should probably abstract this rather than doing a copy-paste job eventually. :laughing:  

I agree this is a nice feature, but recomposing the character into the interface may be a bit complicated. Will check back in.

**Comment by ChristopherDavenport** [comment]
Fixed by #191
