### ISSUE TITLE
Upgrade Plans (cats-effect 3 and friends)

### ISSUE THREAD

**Issue by valencik** [davenverse/cormorant#433]
While trying to upgrade to cats-effect 3.x in https://github.com/davenverse/cormorant/pull/432, I hit a few snags.
I'm thinking about the following plan for updating the current 0.5 series and releasing a new 0.6 series:

## Common
- Update sbt
- Migrate to mdoc
- Update kind-projector
- Update Scala 2.12
- Update Scala 2.13

## Cormorant 0.5
- Scala 2.12 + 2.13
- Cats-effect 2
- Fs2 2
- Http4s 0.22

## Cormorant 0.6
- Scala 2.12 + 2.13
- Cats-effect 3
- Fs2 3
- Http4s 1.0

**Comment by kubukoz** [comment]
@ChristopherDavenport wdyt? I think I'd go straight to what's described as `0.6` here (except http4s 1.0 -> 0.23).

**Comment by kubukoz** [comment]
Another thing possibly worth considering is replacing Atto with cats-parse (Atto is so slow its benchmarks were disabled in cats-parse it seems: https://github.com/typelevel/cats-parse/blob/45893784ef9514eafaa7a5ff57f8dd5339fcd112/bench/src/main/scala/cats/parse/bench/JsonBench.scala#L37).

**Comment by valencik** [comment]
I'd really like to do the atto -> cats-parse work. But it should not block a CE3 compatible release ideally.

I'm cool with jumping to 0.6.

Not noted above but realized recently is that we'll have to migrate off specs2 for a CE3 release.

**Comment by kubukoz** [comment]
What's the problem with specs2?

**Comment by ChristopherDavenport** [comment]
Yes. Although I think cats-parse will be easier than presently expected.

**Comment by ChristopherDavenport** [comment]
I love munit now, but I don't care about testing framework. Anything works.

**Comment by ChristopherDavenport** [comment]
Both 0.5 and 0.6 should be able to have scala 3 support as well. So we should atleast try to confirm that it is possible without a source change.

**Comment by kubukoz** [comment]
so we probably need to do 0.5, then scala 3 support, then the updates for 0.6?

**Comment by valencik** [comment]
Updated https://github.com/davenverse/cormorant/pull/453 to use http4s 0.23.x instead of 1.x

> What's the problem with specs2?

@kubukoz The issue with specs2 is just that it doesn't have a cats-effect 3.x compatible release, or rather, the following two tests fail when we bump to CE3: https://github.com/davenverse/cormorant/pull/453/files#diff-57fe09de1c9eb9a06060dcf9702e8e484234a9f1972ac3bc9ebfcb96a838933aL94-L114


I'll look into migrating to munit today.

**Comment by valencik** [comment]
PR to migrate tests to munit is up: https://github.com/davenverse/cormorant/pull/464

Once merged I'll rebase and clean up the CE3 migration PR https://github.com/davenverse/cormorant/pull/453
